IF(DB_ID(N'Proiect_TW') IS NULL)
	CREATE DATABASE Proiect_TW
GO

USE Proiect_TW
GO

IF OBJECT_ID('Users') IS NULL
CREATE TABLE Users 
(
	UserId INT NOT NULL IDENTITY(1,1),
	UserName NVARCHAR(100) NOT NULL,
	UserEmail NVARCHAR(100) NOT NULL,
	UserPassword NVARCHAR(100) NOT NULL,
	UserMP bit NOT NULL DEFAULT (1),
	UserTester  bit NOT NULL DEFAULT (0),
	CONSTRAINT PK_User PRIMARY KEY (UserId)
)
GO

IF OBJECT_ID('Bugs') IS NULL
CREATE TABLE Bugs 
(
	BugId INT NOT NULL IDENTITY(1,1),
	BugName NVARCHAR(100) NOT NULL,
	BugSeverity NVARCHAR(100) NOT NULL,
	BugPriority NVARCHAR(100) NOT NULL,
	BugDescription NVARCHAR(100) NOT NULL,
	BugLink NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_Bug PRIMARY KEY (BugId)
)

GO

IF OBJECT_ID('Reports') IS NULL
CREATE TABLE Reports 
(
	ReportId INT NOT NULL IDENTITY(1,1),
	ReportDate NVARCHAR(100) NOT NULL,
	ReportDescription NVARCHAR(100) NOT NULL,
	BugId INT NOT NULL,
	UserId INT NOT NULL,
	CONSTRAINT PK_Report PRIMARY KEY (ReportId)
)

IF OBJECT_ID('FK_Report_User') IS NULL
	ALTER TABLE Reports ADD CONSTRAINT FK_Report_User FOREIGN KEY (UserId) REFERENCES Users(UserId)

GO

IF OBJECT_ID('FK_Report_Bug') IS NULL
	ALTER TABLE Reports ADD CONSTRAINT FK_Report_Bug FOREIGN KEY (BugId) REFERENCES Bugs(BugId)

GO

IF OBJECT_ID('StatusBug') IS NULL
CREATE TABLE StatusBug
(
	StatusId INT NOT NULL IDENTITY(1,1),
	StatusText NVARCHAR(100) NOT NULL,
	BugId INT NOT NULL,
	CONSTRAINT PK_Status PRIMARY KEY (StatusId)
)
GO

IF OBJECT_ID('FK_Status_Bug') IS NULL
	ALTER TABLE StatusBug ADD CONSTRAINT FK_Status_Bug FOREIGN KEY (BugId) REFERENCES Bugs(BugId)

